<?php
// Include the autoload.php file generated by Composer. This file is responsible for automatically loading PHP classes.
require 'vendor/autoload.php';

// Create an instance of the Dotenv class. This class is used to load environment variables from a .env file.
// The createImmutable method creates a new Dotenv instance that treats environment variables as immutable.
// Immutable means that existing environment variables will not be overwritten.
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);

// Load the environment variables from the .env file into the environment.
$dotenv->load();

// Retrieve the database host, port, user, password, and name from the environment variables.
$servername = $_ENV['DB_HOST'];
$port = $_ENV['DB_PORT'];
$username = $_ENV['DB_USER'];
$password = $_ENV['DB_PASS'];
$dbname = $_ENV['DB_NAME'];

// Create a new connection to the MySQL server using the mysqli class.
// The mysqli class represents a connection between PHP and a MySQL database.
$conn = new mysqli($servername, $username, $password, $dbname, $port);

// Check if the connection was successful.
// If there was a connection error, the connect_error property of the mysqli object will be set.
if ($conn->connect_error) {
  // If there was a connection error, terminate the script and display an error message.
  die("Connection failed: " . $conn->connect_error);
}

// If the script has not been terminated at this point, the connection was successful.
echo "Connected successfully";
?>
